name: CLI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: 🧪 Test the CLI on ${{ matrix.runtime }} under ${{ matrix.os }} using ${{ matrix.pm }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    timeout-minutes: 60
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        experimental: [false]
        runtime: [node, deno, bun]
        pm: ["", pnpm, yarn]

    steps:
      - name: 🚚 Checkout repository
        uses: actions/checkout@v5

      - name: 🔥 Remove lockfile
        run: rm pnpm-lock.yaml
        shell: bash

      - name: 📦️ Install Panam
        run: npm i -g panam-cli

      - name: Setup Volta Proxy (vp)
        uses: voidzero-dev/setup-vp@v1
        with:
          node-version: "24"
          cache: true

      - name: Setup Test Environment
        uses: siguici/setup-js@v1
        with:
          runtime: ${{ matrix.runtime }}
          pm: ${{ matrix.pm }}
          scripts: build,test
